# Site
name: "Trans Histories in Latin America"
title: "Trans Histories in Latin America"
description: "Blog on trans issues and history in Latin America"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  carson:
    name: Carson
    display_name: Carson Herness
    gravatar: ac560d1e105e432468a141c03f374007
    email: cherness@g.hmc.edu
    description: "Computer Science major at Harvey Mudd College"
    web: https://github.com/CarsonHerness/
    bio: "Carson is a junior computer science major at Harvey Mudd College. In Fall 2019 he studied abroad in Quito, Ecuador and worked with Proyecto Transgenero, a local organization working with transgender people."
  vi:
    name: Vi
    display_name: Vi Nguyen
    gravatar: eab12af4d916249cad26af4ff67907af
    email: vnguyen21@cmc.edu
    description: "Junior studying Government and History at Claremont McKenna College"
    bio: "Vi is a Junior studying Government and History at Claremont McKenna College. She is currently taking a course on Gender and Sexuality in Latin America which sparked her interest in creating a blog about the trans experience in Latin America. Vi enjoys using her majors to analyze civil rights movements and their impacts on political institutions."
  becky:
    name: Becky
    display_name: Becky Chung
    descripton: "Senior at Claremont McKenna majoring in government and history"
    gravatar: f5b58374a3e593abd06977640a980f99
    bio: "Becky is a senior at Claremont McKenna College currently writing her thesis."

  jordy:
    name: Jordy
    display_name: Jordy
    gravatar: 62a592d75b18fe3ef4f5553aa1c87cd5
    description: "Junior at Pomona College. (she/her/hers)"
    bio: "Jordy is a junior at Pomona College."
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: 
adsense-data-ad-slot: 

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
